#!/usr/bin/env bash
# ==============================================================================
#  EYE Analytics — Free SSL Setup (Let's Encrypt + Certbot)
#
#  Run this ONCE on the server after your DNS A-record points to this server:
#    ssh root@YOUR_SERVER_IP
#    cd /opt/eye && bash ssl-setup.sh
#
#  What it does:
#    1. Verifies DNS is pointing here
#    2. Installs certbot and obtains a certificate
#    3. Creates docker-compose.override.yml (gitignored) → adds port 443 +
#       /etc/letsencrypt mount to nginx without touching docker-compose.yml
#    4. Generates docker/nginx/default.conf from the HTTPS template
#    5. Restarts nginx and tests HTTPS
#    6. Sets up daily auto-renewal cron
# ==============================================================================
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
G='\033[0;32m'; Y='\033[1;33m'; C='\033[0;36m'; R='\033[0;31m'; N='\033[0m'
info()    { echo -e "${C}[➜]${N} $*"; }
success() { echo -e "${G}[✓]${N} $*"; }
warn()    { echo -e "${Y}[!]${N} $*"; }
die()     { echo -e "${R}[✗] $*${N}" >&2; exit 1; }

INSTALL_DIR="/opt/eye"
cd "$INSTALL_DIR"

# ── Read domain + email ───────────────────────────────────────────────────────
DOMAIN=$(grep '^APP_URL=' backend/.env | sed 's|APP_URL=https\?://||' | tr -d '"' | tr -d "'" | sed 's|/.*||')
[[ -z "$DOMAIN" ]] && read -rp "Enter your domain (e.g. eye-analysis.live): " DOMAIN
[[ -z "$DOMAIN" ]] && die "Domain required"

EMAIL=$(grep '^MAIL_FROM_ADDRESS=' backend/.env 2>/dev/null | cut -d= -f2 | tr -d '"' | tr -d "'" || true)
[[ -z "$EMAIL" ]] && read -rp "Enter your email for Let's Encrypt notifications: " EMAIL
[[ -z "$EMAIL" ]] && die "Email required"

info "Domain : $DOMAIN"
info "Email  : $EMAIL"

# ── Verify DNS ────────────────────────────────────────────────────────────────
info "Checking DNS for $DOMAIN ..."
SERVER_IP=$(curl -4s --max-time 5 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
DNS_IP=$(dig +short @8.8.8.8 "$DOMAIN" 2>/dev/null | grep -E '^[0-9]+\.' | tail -1 || true)

if [[ "$DNS_IP" != "$SERVER_IP" ]]; then
    warn "DNS check: $DOMAIN → '${DNS_IP:-<no record>}'  (this server: $SERVER_IP)"
    warn "DNS is NOT pointing to this server yet."
    warn "Add an A record:  $DOMAIN → $SERVER_IP  (and www.$DOMAIN → $SERVER_IP)"
    read -rp "Continue anyway? (type 'yes' if DNS is already propagated) " CONFIRM
    [[ "$CONFIRM" != "yes" ]] && die "Aborted. Fix DNS first, then re-run."
else
    success "DNS OK: $DOMAIN → $SERVER_IP"
fi

# ── Install Certbot ───────────────────────────────────────────────────────────
info "Installing certbot..."
apt-get update -qq
apt-get install -y -qq certbot dnsutils
success "Certbot ready: $(certbot --version 2>&1)"

# ── Stop nginx so certbot standalone can bind port 80 ─────────────────────────
info "Stopping nginx container temporarily..."
docker compose stop nginx

# ── Obtain certificate ────────────────────────────────────────────────────────
info "Requesting certificate for $DOMAIN and www.$DOMAIN ..."
certbot certonly \
  --standalone \
  --non-interactive \
  --agree-tos \
  --email "$EMAIL" \
  -d "$DOMAIN" \
  -d "www.$DOMAIN" \
  --expand
success "Certificate obtained at /etc/letsencrypt/live/$DOMAIN/"

# ── Generate HTTPS nginx config from template ─────────────────────────────────
info "Generating HTTPS nginx config..."
sed "s/DOMAIN/$DOMAIN/g" docker/nginx/default.conf.ssl > docker/nginx/default.conf
success "docker/nginx/default.conf updated for HTTPS"

# ── Create docker-compose.override.yml ────────────────────────────────────────
# This file is gitignored and auto-merged by `docker compose` on the server.
# It overrides only the nginx ports and adds the cert volume mount.
info "Creating docker-compose.override.yml..."
cat > docker-compose.override.yml <<EOF
# Auto-generated by ssl-setup.sh — DO NOT COMMIT (gitignored)
# Overrides nginx service on this server to enable HTTPS.
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
EOF
success "docker-compose.override.yml created"

# ── Restart nginx with new config + override ─────────────────────────────────
info "Starting nginx with HTTPS..."
docker compose up -d nginx

sleep 4
docker compose ps nginx

# ── Test HTTPS ────────────────────────────────────────────────────────────────
info "Testing HTTPS endpoint..."
sleep 2
HTTP_CODE=$(curl -sk --max-time 10 -o /dev/null -w "%{http_code}" "https://$DOMAIN/api/health" || echo "000")
if [[ "$HTTP_CODE" == "200" || "$HTTP_CODE" == "301" || "$HTTP_CODE" == "302" ]]; then
    success "HTTPS is working! Status: $HTTP_CODE"
else
    warn "HTTPS test returned: $HTTP_CODE"
    warn "Check logs: docker compose logs nginx --tail=30"
fi

# ── Setup auto-renewal cron ───────────────────────────────────────────────────
info "Setting up auto-renewal cron (daily at 3:00 AM)..."
CRON_CMD="0 3 * * * cd $INSTALL_DIR && docker compose stop nginx && certbot renew --quiet && docker compose start nginx"
(crontab -l 2>/dev/null | grep -v "certbot renew"; echo "$CRON_CMD") | crontab -
success "Auto-renewal cron installed"

echo ""
echo -e "${G}══════════════════════════════════════════════════════${N}"
echo -e "${G}  SSL setup complete!${N}"
echo -e "${G}  https://$DOMAIN${N}"
echo -e "${G}  Certificate renews automatically every 90 days${N}"
echo -e "${G}══════════════════════════════════════════════════════${N}"
