#!/usr/bin/env bash
#
# EYE — production deploy (runs ON the VPS, in the repo directory).
# This replaces the GitHub Actions SSH step so deploys work without CI minutes.
#
# Usage (on the server):   cd /path/to/eye && bash scripts/deploy.sh
# Or trigger from your machine with scripts/remote-deploy.sh
#
# It pulls the latest code from GitHub (git itself is free — only Actions was
# billed), updates submodules, then runs the same Docker/Laravel/Next/tracker
# steps the old pipeline did.
set -euo pipefail

# Move to the repo root (parent of this scripts/ dir) regardless of CWD.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export COMPOSE_FILE=docker-compose.prod.yml

log() { echo -e "\n==> $*"; }

log "Pulling latest code..."
if ! git pull --rebase --autostash origin main; then
  log "WARNING: pull failed — backing up and resetting to origin/main..."
  TS=$(date +%Y%m%d-%H%M%S)
  git branch "backup/pre-reset-$TS" || true
  git stash push -u -m "pre-reset-$TS" || true
  git fetch origin main
  git reset --hard origin/main
fi

log "Updating submodules (backend=main, frontend=master)..."
git submodule sync --recursive
(cd backend  && git fetch origin main   && git reset --hard origin/main)
(cd frontend && git fetch origin master && git reset --hard origin/master)

log "[BACKEND] composer install..."
docker compose exec -T php-fpm composer install \
  --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs

log "[BACKEND] Running migrations..."
docker compose exec -T php-fpm php artisan migrate --force

log "[BACKEND] Restarting php-fpm + workers..."
docker compose restart php-fpm
docker compose exec -T php-fpm php artisan horizon:terminate || true
# --force-recreate, not restart: env_file is read only when a container is
# CREATED, so a plain restart keeps whatever environment the container was born
# with. eye_scheduler ran for four months on a four-month-old .env that way,
# mailing from a domain that had since been retired.
docker compose up -d --force-recreate --no-deps laravel-horizon laravel-scheduler laravel-reverb

log "[BACKEND] Recaching config & routes..."
docker compose exec -T php-fpm php artisan config:clear
docker compose exec -T php-fpm php artisan config:cache
docker compose exec -T php-fpm php artisan route:clear
docker compose exec -T php-fpm php artisan route:cache
docker compose exec -T php-fpm php artisan view:clear
docker compose exec -T php-fpm php artisan storage:link --force

log "[FRONTEND] Rebuilding Next.js container..."
set -a; [ -f frontend/.env.local ] && source frontend/.env.local; set +a
docker compose up -d --build --force-recreate node

log "[TRACKER] Rebuilding tracker bundle..."
docker compose up -d --no-deps tracker-build

log "Restarting nginx..."
docker compose restart nginx

# Restore HTTPS nginx config if certs exist for the configured domain.
DOMAIN=$(grep '^APP_URL=' backend/.env 2>/dev/null | sed 's|APP_URL=https\?://||' | tr -d '"' | sed 's|/.*||' || true)
if [ -n "${DOMAIN:-}" ] && [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
  log "[SSL] Restoring HTTPS nginx config for $DOMAIN..."
  # Stamp the output so anyone who opens the deployed file sees it is generated
  # and edits the template instead — hand-edits here are wiped by every deploy.
  {
    echo "# GENERATED by scripts/deploy.sh from docker/nginx/default.conf.ssl on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# DO NOT EDIT — changes are destroyed on the next deploy. Edit default.conf.ssl."
    echo
    sed "s/DOMAIN/$DOMAIN/g" docker/nginx/default.conf.ssl
  } > docker/nginx/default.conf.new

  # Validate before swapping: a broken config that nginx refuses would take the
  # whole site down on restart.
  cp docker/nginx/default.conf docker/nginx/default.conf.prev
  mv docker/nginx/default.conf.new docker/nginx/default.conf
  if docker compose exec -T nginx nginx -t >/dev/null 2>&1; then
    docker compose restart nginx
  else
    log "[SSL] Generated nginx config FAILED validation — rolling back."
    mv docker/nginx/default.conf.prev docker/nginx/default.conf
    docker compose restart nginx
    docker compose exec -T nginx nginx -t || true
  fi
  rm -f docker/nginx/default.conf.prev
fi

log "Health check..."
sleep 5
curl -sf http://localhost/api/v1/health && echo "Health: OK" || echo "WARNING: health check failed"

# Tracker smoke test. These paths must never redirect: a browser following a
# 301 on a POST rewrites it into a GET, which /api/collect answers with 405,
# and every customer event is lost silently — one site went dark for a week
# that way before anyone noticed. 401 is the expected answer to a bogus token;
# anything else (301, 405) means the routing is broken again.
if [ -n "${DOMAIN:-}" ]; then
  for host in "$DOMAIN" "www.$DOMAIN"; do
    code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://$host/api/collect"       -H 'Content-Type: application/json' -d '{"t":"deploy-smoke-test","e":"pageview"}' || echo 000)
    case "$code" in
      2*|401|422) echo "Tracker OK on $host ($code)" ;;
      *) echo "WARNING: $host /api/collect returned $code — expected 401. Tracking may be broken." ;;
    esac

    acao=$(curl -s -D- -o /dev/null "https://$host/api/v1/experiments/active?t=smoke"       -H 'Origin: https://example.com' | grep -ci 'access-control-allow-origin: \*' || true)
    [ "$acao" = "1" ]       && echo "Experiments CORS OK on $host"       || echo "WARNING: $host experiments/active is missing Access-Control-Allow-Origin: * — A/B will not run on customer sites."
  done
fi

docker image prune -f
log "Deployment complete!"
